- name: create postgresql users
  postgresql_user:
    db: "{{ postgresql_db_name }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    login_host: "{{ postgresql_ports[0].split(':')[0] }}"
    port: "{{ postgresql_ports[0].split(':')[1] }}"
    login_user: "{{ postgresql_user_name }}"
    login_password: "{{ postgresql_user_password }}"
  loop: "{{ postgresql_users }}"

- name: set postgresql users privs
  postgresql_privs:
    db: "{{ postgresql_db_name }}"
    role: "{{ item.name }}"
    objs: ALL_IN_SCHEMA
    privs: "{{ item.priv }}"
    login_host: "{{ postgresql_ports[0].split(':')[0] }}"
    login_user: "{{ postgresql_user_name }}"
    login_password: "{{ postgresql_user_password }}"
  loop: "{{ postgresql_users }}"