postgresql_image: postgres
postgresql_image_tag: 11.4
postgresql_exporter_image: wrouesnel/postgres_exporter
postgresql_exporter_image_tag: v0.5.1

postgresql_containers:
  - name: postgresql
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    published_ports:
      - "127.0.0.1:5432:5432"

postgresql_users:
  - name: reader
    password: reader
    priv: SELECT
  - name: writer
    password: writer
    priv: ALL

postgresql_exporter_containers:
  - name: postgresql_exporter
    published_ports:
      - "127.0.0.1:9187:9187"